### ISSUE TITLE
please , answer these comments

### ISSUE THREAD

**Issue by salem23** [salem23/ConfofGames2019#42]
Please Antonio, could you reply these comments, 

1. - reduced diversity is good (1) -> usually, the opposite is true in my experience
2. - What does "map the trajectory" mean?
3. - It is not clear whether the statistics about the articles cited are about TORCS or not? And if they aren't, why are they relevant?
4. - 	"in this environment is quite hard" -> very vague

**Comment by amorag** [comment]
I'm working on them.

However, I'm not really sure what we meant in the first statement.

It is said in the text:
"This reduction of uncertainty has been proved also to reduce diversity in the genetic pool" and a citation to our work about uncertainty in games

Do we mean it is possitive? In which sense? 
Since increase diversity is one of the aims of the genetic process in order to avoid premature convergence.

@JJ could you have a look and this comment?

Thanks!

**Comment by JJ** [comment]
El mié., 29 jul. 2020 a las 12:56, Antonio Mora (<notifications@github.com>)
escribió:

> I'm working on them.
>
> However, I'm not really sure what we meant in the first statement.
>
> It is said in the text:
> "This reduction of uncertainty has been proved also to reduce diversity in
> the genetic pool" and a citation to our work about uncertainty in games
>

It's our statement in our paper, and a reference to our work. You can also
try and find out.

**Comment by amorag** [comment]
Ok, thank you.

**Comment by JJ** [comment]
No substantial revision of the text is made, or itemized and atomic commits for every question.
