### ISSUE TITLE
Rev 2,  Comment 4 

### ISSUE THREAD

**Issue by salem23** [salem23/ConfofGames2019#43]
"The best way to reduce uncertainty is to make the evaluation process as close as possible to the environment in which the controller will eventually compete, in a race with other competitors." -> This is the best way?

**Comment by amorag** [comment]
Well I have to check what we did, because, if I'm not wrong, we trained the controllers in solo races, which is the opposite we are saying in that text... 
Maybe we meant that it would be better to train in the same conditions that in real races in order to obtain a competitive controller, however the inclusion of rivals during training will lead to add more sources of noise/uncertainty... 
Don't you think? @salem23 @JJ

**Comment by JJ** [comment]
Please expand a bit the title of every issue with a general description of it, so that it's possible to get what it's about just by checking out the title.
